version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "No dependencies!"
  build:
    commands:
      - zip -r9 ./index.zip ./index-photos.py
      - ls
      - zip -r9 ./search.zip ./search-photos.py
  post_build:
    commands:
      - echo "Updating lambdas"
      - aws lambda update-function-code --function-name index-photos2 --zip-file fileb://index.zip
      - aws lambda update-function-code --function-name search-photos2 --zip-file fileb://search.zip
      - echo "Updates completed"
