Parameters:
  BucketName:
    Type: String
    Default: b2-photos-zero-cf
  PrivateSubnet:
    Description: Choose which subnets the Lambda-functions should be deployed to
    Type: AWS::EC2::Subnet::Id
    Default: subnet-08034b18ca6b04788
  SecurityGroup:
    Description: Select the Security Group to use for the Lambda-functions
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-09d3b32ac839df60b

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This Lambda function does something
Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body: ./api.yaml
      Name : test-api
    
