AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This Lambda function does something
Resources:
  IndexLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                  - 's3-object-lambda:*'
                Resource:
                  - '*'
        - PolicyName: AmazonRekognitionFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'rekognition:*'
                Resource:
                  - '*'
        - PolicyName: AmazonOpenSearchServiceFullAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'es:*'
                Resource:
                  - '*'
      Path: /
  IndexLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index-photos.lambda_handler'
      MemorySize: '256'
      Description: It is a Lambda function
      FunctionName: 'index-photos-3'
      Role: !GetAtt 
        - IndexLambdaRole
        - Arn
      Runtime: python3.9
      Timeout: '60'
      Code: ./index-photos.py
    DependsOn:
      - IndexLambdaRole
  
  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt IndexLambda.Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::773710002038'
      SourceArn: !Sub 'arn:aws:s3:::b2-foto'
  
  LambdaTrigger:
    Type: 'Custom::LambdaTrigger'
    DependsOn: LambdaInvokePermission
    Properties:
      ServiceToken: !GetAtt IndexLambda.Arn
      LambdaArn: !GetAtt IndexLambda.Arn
      Bucket: !Ref b2-foto
